//
//  PatientDetailPresenter.swift
//  IsCleanSwiftClean
//
//  Created by Jordan Rilassi on 18/09/2019.
//  Copyright (c) 2019 Jordan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PatientDetailPresentationLogic
{
    func presentPatientDetail(response: PatientDetail.Patient.Response)
}

class PatientDetailPresenter: PatientDetailPresentationLogic
{
    weak var viewController: PatientDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentPatientDetail(response: PatientDetail.Patient.Response)
    {
        let fullName = "\(response.firstName) \(response.lastName)"
        let viewModel = PatientDetail.Patient.ViewModel(fullName: fullName, avatarImage: response.gender.image)
        viewController?.displayPatientDetail(viewModel: viewModel)
    }
}
