//
//  PatientDetailWorker.swift
//  IsCleanSwiftClean
//
//  Created by Jordan Rilassi on 18/09/2019.
//  Copyright (c) 2019 Jordan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PatientDetailWorker
{
    func fetchPatient(patientId: String) -> PatientDetail.Patient.Response? {
        guard let patient = PatientDBRepository().fetchPatient(with: patientId) else { return nil }
        return PatientDetail.Patient.Response(firstName: patient.firstName, lastName: patient.lastName, gender: patient.gender)
    }
}
