//
//  PatientDetailInteractor.swift
//  IsCleanSwiftClean
//
//  Created by Jordan Rilassi on 18/09/2019.
//  Copyright (c) 2019 Jordan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PatientDetailBusinessLogic
{
    func doSomething(request: PatientDetail.Something.Request)
}

protocol PatientDetailDataStore
{
    //var name: String { get set }
}

class PatientDetailInteractor: PatientDetailBusinessLogic, PatientDetailDataStore
{
    var presenter: PatientDetailPresentationLogic?
    var worker: PatientDetailWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: PatientDetail.Something.Request)
    {
        worker = PatientDetailWorker()
        worker?.doSomeWork()
        
        let response = PatientDetail.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
