//
//  PatientDetailInteractor.swift
//  IsCleanSwiftClean
//
//  Created by Jordan Rilassi on 18/09/2019.
//  Copyright (c) 2019 Jordan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PatientDetailBusinessLogic
{
    func fetchPatientDetail(request: PatientDetail.Patient.Request)
}

protocol PatientDetailDataStore
{
    var patientId: String { get set }
}

class PatientDetailInteractor: PatientDetailBusinessLogic, PatientDetailDataStore
{
    var presenter: PatientDetailPresentationLogic?
    var worker: PatientDetailWorker?
    var patientId: String = ""
    
    // MARK: Do something
    
    func fetchPatientDetail(request: PatientDetail.Patient.Request)
    {
        worker = PatientDetailWorker()
        guard let response = worker?.fetchPatient(patientId: patientId) else {
            // Handle error here
            return
        }
        presenter?.presentPatientDetail(response: response)
    }
}
